version: "3"
services:

    canal-admin:
        image: canal/canal-admin:v1.1.4
        ports:
        - "8089:8089"
        environment:
        - canal.adminUser=admin
        - canal.adminPasswd=admin
        volumes:
        - "./admin_data:/home/admin/canal-admin/logs"
    
    canal-server:
        image: canal/canal-server:v1.1.4
        ports:
        - "11110:11110"
        environment:
        - canal.admin.manager=canal-admin:8089
        - canal.admin.user=admin
        - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
        volumes:
        - "./data:/home/admin/canal-server/logs"
        depends_on:
        - canal-admin
