version: "3"
services:
    
    parse-server:
        image: parse-server:latest
        environment:
            - PARSE_SERVER_APPLICATION_ID=appId
            - PARSE_SERVER_MASTER_KEY=masterKey
            - PARSE_SERVER_DATABASE_URI=mongodb://mongo/test
            
        ports:
            - 1337:1337
        depends_on:
            - mongo
            
    mongo:
        image: mongo:latest
        